# Generated by Django 3.2.7 on 2023-04-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_by_weather', '0002_usersave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersave',
            name='songs',
            field=models.TextField(),
        ),
    ]
