# Generated by Django 4.1.7 on 2023-04-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_by_weather', '0004_musician_remove_movie_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('url', models.CharField(max_length=256, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='recommended_songs',
            field=models.ManyToManyField(max_length=2048, to='song_by_weather.song'),
        ),
        migrations.AddField(
            model_name='usersave',
            name='IDs',
            field=models.ManyToManyField(to='song_by_weather.song'),
        ),
    ]
