# Generated by Django 4.1.7 on 2023-05-05 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_by_weather', '0006_alter_user_age_alter_user_dob_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='dob',
            field=models.DateField(default=datetime.date(2023, 5, 5), max_length=1028),
        ),
    ]
