# Generated by Django 4.1.7 on 2023-05-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song_by_weather', '0007_alter_user_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='hometown',
            field=models.IntegerField(default=0, max_length=64),
        ),
    ]
